#!/usr/bin/env bash

db=./db/

if [ ! -z $1 ]; then
    if [ $1 == "create" ]; then
        initdb $db
    elif [ $1 == "start" ]; then
        pg_ctl -D $db -l logfile start
    elif [ $1 == "stop" ]; then
        pg_ctl -D $db stop
    elif [ $1 == "status" ]; then
        pg_ctl -D $db status
    elif [ $1 == "list" ]; then
        psql -l
    fi
fi
