#!/usr/bin/env bash

set -eu

flags=(
    "-ferror-limit=1"
    -ffast-math
    -fno-autolink
    -fno-exceptions
    -fno-math-errno
    -fno-omit-frame-pointer
    -fno-rtti
    -fno-unwind-tables
    "-fsanitize=address"
    "-fsanitize=undefined"
    -fshort-enums
    "-I${PATH_PG}/include"
    "-L${PATH_LIBPG}/lib"
    -lpq
    "-march=native"
    -O1
    "-std=c++11"
    -Werror
    -Weverything
    -Wno-c++20-designator
    -Wno-c++98-compat
    -Wno-extra-semi-stmt
)

if [ ! -d "$WD/bin" ]; then
    mkdir "$WD/bin"
fi

clang-format -i -verbose "$WD/src/"*
clang++ "${flags[@]}" -o "$WD/bin/main" "$WD/src/main.cpp"
"$WD/bin/main"
