#!/usr/bin/env bash

db="$WD/db"

if [ ! -d "$db" ]; then
    mkdir "$db"
fi

case "$1" in
    "create")
        initdb "$db";;
    "start")
        pg_ctl -D "$db" -l "$WD/db_log" "start";;
    "stop")
        pg_ctl -D "$db" "stop";;
    "status")
        pg_ctl -D "$db" "status";;
    "list")
        psql -l;;
    *)
        ;;
esac
